In [34]:
import numpy as np
import pandas as pd
from tqdm import tqdm
import matplotlib.pyplot as plt
from astropy.time import Time 
namelist = ['2003MA3','2010CO1','2010DG77','2010EX11','2010FC81','2010FH81','2010GS7','2010JN71','2010KX7','2010PW58','2010XP69','2019DD2']
nlist = ['1994cb','1996gq','2002lt24', '2008np3', '2009ux17' ,'2010aj30', '2010bh115' ,'2010ca55' ,'2010cc55' ,'2010cn141','2010dh77' ,'2010fa81' ,'2010gp67' ,'2010hw81' ,'2010hx107', '2010hz104' ,'2010jx16', '2010kp10' ,'2010ku7' ,'2010lh14' ,'2010lj68' ,'2010lk68' ,'2010ll68' ,'2010lv108' ,'2010ns36', '2010ny65', '2010oh126', '2010pu66' ,'2014fd7' ,'2015tf' ,'2016uh101']
alist = namelist + nlist

In [35]:
name = alist[3].lower()
print(name)
rawdata = pd.read_csv(f'{name}.csv')
rawdata = rawdata.loc[:,['mjd','w1mpro','w1sigmpro','w2mpro','w2sigmpro','w3mpro','w3sigmpro','w4mpro','w4sigmpro','ph_qual','sso_flg']]
rawdata.insert(loc=len(rawdata.columns),column='tdbjd',value='no')
rawdata.insert(loc=len(rawdata.columns),column='tdbmjd',value='no')
#rawdata['mjd'] = 2400000.5+rawdata['mjd']
for i in tqdm(range(len(rawdata))):  
    t = Time(rawdata['mjd'][i],format='mjd',scale='utc')
    t.format = 'iso'
    rawdata['tdbjd'][i] = t.tdb.jd
    rawdata['tdbmjd'][i] = t.tdb.mjd
rawdata
data = rawdata.loc[:,['tdbjd','w1mpro','w1sigmpro','w2mpro','w2sigmpro','w3mpro','w3sigmpro','w4mpro','w4sigmpro']]
data1234 = data.loc[:,['w1mpro','w1sigmpro','w2mpro','w2sigmpro','w3mpro','w3sigmpro','w4mpro','w4sigmpro']]
data1234[:5]

2010ex11

  0%|          | 0/15 [00:00<?, ?it/s]/tmp/ipykernel_5505/2675325604.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rawdata['tdbjd'][i] = t.tdb.jd
/tmp/ipykernel_5505/2675325604.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rawdata['tdbmjd'][i] = t.tdb.mjd
100%|██████████| 15/15 [00:00<00:00, 1298.25it/s]

   w1mpro  w1sigmpro  w2mpro  w2sigmpro  w3mpro  w3sigmpro  w4mpro  w4sigmpro
0  16.719        NaN  15.034        NaN  10.322      0.165   7.395        NaN
1  17.235        NaN  15.479        NaN  10.173      0.145   6.827      0.188
2  17.140        NaN  15.710        NaN  10.093      0.145   7.735        NaN
3  17.179        NaN  15.445      0.422  10.078      0.143   7.535        NaN
4  17.212        NaN  14.779      0.273  10.068      0.151   7.727      0.445

In [36]:
data1234.insert(loc=len(data1234.columns),column='w1nan',value=0)
data1234.insert(loc=len(data1234.columns),column='w2nan',value=0)
data1234.insert(loc=len(data1234.columns),column='w3nan',value=0)
data1234.insert(loc=len(data1234.columns),column='w4nan',value=0)

In [37]:
for i in range(len(data1234)):
    if data1234.loc[i,'w1sigmpro']>0:
        data1234.loc[i,'w1nan'] = 1
    else:
        data1234.loc[i,'w1sigmpro'] = 0.01
    if data1234.loc[i,'w2sigmpro']>0:
        data1234.loc[i,'w2nan'] = 1
    else:
        data1234.loc[i,'w2sigmpro'] = 0.01
    if data1234.loc[i,'w3sigmpro']>0:
        data1234.loc[i,'w3nan'] = 1
    else:
        data1234.loc[i,'w3sigmpro'] = 0.01
    if data1234.loc[i,'w4sigmpro']>0:
        data1234.loc[i,'w4nan'] = 1
    else:
        data1234.loc[i,'w4sigmpro'] = 0.01
data1234[:5]

,w1mpro,w1sigmpro,w2mpro,w2sigmpro,w3mpro,w3sigmpro,w4mpro,w4sigmpro,w1nan,w2nan,w3nan,w4nan
0,16.719,0.01,15.034,0.010,10.322,0.165,7.395,0.010,0,0,1,0
1,17.235,0.01,15.479,0.010,10.173,0.145,6.827,0.188,0,0,1,1
2,17.140,0.01,15.710,0.010,10.093,0.145,7.735,0.010,0,0,1,0
3,17.179,0.01,15.445,0.422,10.078,0.143,7.535,0.010,0,1,1,0
4,17.212,0.01,14.779,0.273,10.068,0.151,7.727,0.445,0,1,1,1

In [38]:
datafill = data1234.fillna(method='ffill',axis=1).fillna(method='backfill',axis=1)
datafill[:5]

,w1mpro,w1sigmpro,w2mpro,w2sigmpro,w3mpro,w3sigmpro,w4mpro,w4sigmpro,w1nan,w2nan,w3nan,w4nan
0,16.719,0.01,15.034,0.010,10.322,0.165,7.395,0.010,0.0,0.0,1.0,0.0
1,17.235,0.01,15.479,0.010,10.173,0.145,6.827,0.188,0.0,0.0,1.0,1.0
2,17.140,0.01,15.710,0.010,10.093,0.145,7.735,0.010,0.0,0.0,1.0,0.0
3,17.179,0.01,15.445,0.422,10.078,0.143,7.535,0.010,0.0,1.0,1.0,0.0
4,17.212,0.01,14.779,0.273,10.068,0.151,7.727,0.445,0.0,1.0,1.0,1.0

## M2Flux

In [39]:
#-------initial para-------------------------
#Fv0 of W1 ,W2, W3, W4
Fv0 = [-1,306.682,170.663,29.045,8.284]
#Color corrections  Col[Bv=1:8=(100,141,200,283,400,566,800,1131),fc=1:4=(W1,W2,W3,W4)]
Fc0 = np.zeros((1,8))#W1,W2,W3,W4
Fc1 = np.array([-1,17.2062,3.9096,2.6588,1.0032]) #Bv=100
Fc2 = np.array([-1,4.0882,1.9739,1.4002,0.9852])  #Bv=141
Fc3 = np.array([-1,2.0577,1.3448,1.0006,0.9833])  #Bv=200
Fc4 = np.array([-1,1.3917,1.1124,0.8791,0.9865])  #Bv=283
Fc5 = np.array([-1,1.1316,1.0229,0.8622,0.9903])  #Bv=400
Fc6 = np.array([-1,1.0263,0.9919,0.8833,0.9935])  #Bv=566
Fc7 = np.array([-1,0.9884,0.9853,0.9125,0.9958])  #Bv=800
Fc8 = np.array([-1,0.9801,0.9877,0.9386,0.9975])  #Bv=1131
Fc = [Fc0,Fc1,Fc2,Fc3,Fc4,Fc5,Fc6,Fc7,Fc8]
Fc = np.array(Fc)
Bv = 4
Const = np.array([-1,Fv0[1],Fv0[2],Fv0[3],Fv0[4]])
def h2flux(Fconst,dat_H):
    return Fconst*np.power(10,-dat_H/2.5)*1000

/tmp/ipykernel_5505/3900039758.py:15: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  Fc = np.array(Fc)

In [40]:
#data of W1,W2,W3,W4
dat_w1 = np.array(datafill['w1mpro'])
#dat_w1= np.hstack([dat_w1,dat_w1*0.1])
dat_w2 = np.array(datafill['w2mpro'])
#dat_w2= np.hstack([dat_w2,dat_w2*0.1])
dat_w3 = np.array(datafill['w3mpro'])
#dat_w3= np.hstack([dat_w3,dat_w3*0.1])
dat_w4 = np.array(datafill['w4mpro'])
#dat_w4= np.hstack([dat_w4,dat_w4*0.1])
#dat w1
dat_fluxw1 = dat_w1
dat_fluxw1 = Const[1]*np.power(10,-dat_w1/2.5)*1000 
#dat w2
dat_fluxw2 = dat_w2
dat_fluxw2 = Const[2]*np.power(10,-dat_w2/2.5)*1000 
#dat w3
dat_fluxw3 = dat_w3
dat_fluxw3 = Const[3]*np.power(10,-dat_w3/2.5)*1000 
#print(f'{Const[1]}*{np.power(10,-dat_w3[0]/2.5)}*1000={dat_fluxw3[0]}')
#dat w4
dat_fluxw4 = dat_w4
dat_fluxw4 = Const[4]*np.power(10,-dat_w4/2.5)*1000 
dat234 = np.concatenate([dat_fluxw2,dat_fluxw3,dat_fluxw4],axis=0)
#np.savetxt(f'obs.txt.{name}',dat234)
dat1234 = np.concatenate([dat_fluxw1,dat_fluxw2,dat_fluxw3,dat_fluxw4],axis=0)
#np.savetxt(f'obsNEW.txt.{name}',dat1234)
dat1234[:5]

array([0.06296342, 0.03914608, 0.04272561, 0.04121813, 0.03998419])

In [45]:
dat_err1 = np.array(datafill['w1sigmpro'])
err1 = dat_err1
err1 = Const[1]*(-1/2.5)*np.power(10,(-1/2.5)*(dat_w1-1))*1000*dat_err1
err1 = abs(err1)
dat_err2 = np.array(datafill['w2sigmpro'])
err2 = dat_err2
err2 = Const[2]*(-1/2.5)*np.power(10,(-1/2.5)*(dat_w2-1))*1000*dat_err2
err2 = abs(err2)
dat_err3 = np.array(datafill['w3sigmpro'])
err3 = dat_err3
err3 = Const[3]*(-1/2.5)*np.power(10,(-1/2.5)*(dat_w3-1))*1000*dat_err3
err3 = abs(err3)
dat_err4 = np.array(datafill['w1sigmpro'])
err4 = dat_err4
err4 = Const[4]*(-1/2.5)*np.power(10,(-1/2.5)*(dat_w4-1))*1000*dat_err4
err4 = abs(err4)
daterr = np.concatenate([err1,err2,err3,err4],axis=0)
np.savetxt(f'obsNEWerr.txt.{name.upper()}',daterr)
name

'2010ex11'

In [47]:
for i in range(len(alist)):
    namei = alist[i]
    rawdata = pd.read_csv(f'{namei.lower()}.csv')
    rawdata = rawdata.loc[:,['mjd','w1mpro','w1sigmpro','w2mpro','w2sigmpro','w3mpro','w3sigmpro','w4mpro','w4sigmpro','ph_qual','sso_flg']]
    rawdata.insert(loc=len(rawdata.columns),column='tdbjd',value='no')
    rawdata.insert(loc=len(rawdata.columns),column='tdbmjd',value='no')
    #rawdata['mjd'] = 2400000.5+rawdata['mjd']
    for i in tqdm(range(len(rawdata))):  
        t = Time(rawdata['mjd'][i],format='mjd',scale='utc')
        t.format = 'iso'
        rawdata['tdbjd'][i] = t.tdb.jd
        rawdata['tdbmjd'][i] = t.tdb.mjd
    rawdata
    data = rawdata.loc[:,['tdbjd','w1mpro','w1sigmpro','w2mpro','w2sigmpro','w3mpro','w3sigmpro','w4mpro','w4sigmpro']]
    data1234 = data.loc[:,['w1mpro','w1sigmpro','w2mpro','w2sigmpro','w3mpro','w3sigmpro','w4mpro','w4sigmpro']]
    data1234.insert(loc=len(data1234.columns),column='w1nan',value=0)
    data1234.insert(loc=len(data1234.columns),column='w2nan',value=0)
    data1234.insert(loc=len(data1234.columns),column='w3nan',value=0)
    data1234.insert(loc=len(data1234.columns),column='w4nan',value=0)      
    for i in range(len(data1234)):
        if data1234.loc[i,'w1sigmpro']>0:
            data1234.loc[i,'w1nan'] = 1
        else:
            data1234.loc[i,'w1sigmpro'] = 0.01
        if data1234.loc[i,'w2sigmpro']>0:
            data1234.loc[i,'w2nan'] = 1
        else:
            data1234.loc[i,'w2sigmpro'] = 0.01
        if data1234.loc[i,'w3sigmpro']>0:
            data1234.loc[i,'w3nan'] = 1
        else:
            data1234.loc[i,'w3sigmpro'] = 0.01
        if data1234.loc[i,'w4sigmpro']>0:
            data1234.loc[i,'w4nan'] = 1
        else:
            data1234.loc[i,'w4sigmpro'] = 0.01
    datafill = data1234.fillna(method='ffill',axis=1).fillna(method='backfill',axis=1)
    #data of W1,W2,W3,W4
    dat_w1 = np.array(datafill['w1mpro'])
    #dat_w1= np.hstack([dat_w1,dat_w1*0.1])
    dat_w2 = np.array(datafill['w2mpro'])
    #dat_w2= np.hstack([dat_w2,dat_w2*0.1])
    dat_w3 = np.array(datafill['w3mpro'])
    #dat_w3= np.hstack([dat_w3,dat_w3*0.1])
    dat_w4 = np.array(datafill['w4mpro'])
    #dat_w4= np.hstack([dat_w4,dat_w4*0.1])
    #dat w1
    dat_fluxw1 = dat_w1
    dat_fluxw1 = Const[1]*np.power(10,-dat_w1/2.5)*1000 
    #dat w2
    dat_fluxw2 = dat_w2
    dat_fluxw2 = Const[2]*np.power(10,-dat_w2/2.5)*1000 
    #dat w3
    dat_fluxw3 = dat_w3
    dat_fluxw3 = Const[3]*np.power(10,-dat_w3/2.5)*1000 
    #print(f'{Const[1]}*{np.power(10,-dat_w3[0]/2.5)}*1000={dat_fluxw3[0]}')
    #dat w4
    dat_fluxw4 = dat_w4
    dat_fluxw4 = Const[4]*np.power(10,-dat_w4/2.5)*1000 
    dat234 = np.concatenate([dat_fluxw2,dat_fluxw3,dat_fluxw4],axis=0)
    #np.savetxt(f'obs.txt.{name}',dat234)
    dat1234 = np.concatenate([dat_fluxw1,dat_fluxw2,dat_fluxw3,dat_fluxw4],axis=0)
    #np.savetxt(f'obsNEW.txt.{name}',dat1234)
    dat_err1 = np.array(datafill['w1sigmpro'])
    err1 = dat_err1
    err1 = Const[1]*(-1/2.5)*np.power(10,(-1/2.5)*(dat_w1-1))*1000*dat_err1
    err1 = abs(err1)
    dat_err2 = np.array(datafill['w2sigmpro'])
    err2 = dat_err2
    err2 = Const[2]*(-1/2.5)*np.power(10,(-1/2.5)*(dat_w2-1))*1000*dat_err2
    err2 = abs(err2)
    dat_err3 = np.array(datafill['w3sigmpro'])
    err3 = dat_err3
    err3 = Const[3]*(-1/2.5)*np.power(10,(-1/2.5)*(dat_w3-1))*1000*dat_err3
    err3 = abs(err3)
    dat_err4 = np.array(datafill['w1sigmpro'])
    err4 = dat_err4
    err4 = Const[4]*(-1/2.5)*np.power(10,(-1/2.5)*(dat_w4-1))*1000*dat_err4
    err4 = abs(err4)
    daterr = np.concatenate([err1,err2,err3,err4],axis=0)
    np.savetxt(f'obsNEWerr.txt.{namei.upper()}',daterr)

  0%|          | 0/8 [00:00<?, ?it/s]/tmp/ipykernel_5505/349492689.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rawdata['tdbjd'][i] = t.tdb.jd
/tmp/ipykernel_5505/349492689.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rawdata['tdbmjd'][i] = t.tdb.mjd
100%|██████████| 8/8 [00:00<00:00, 891.91it/s]
100%|██████████| 32/32 [00:00<00:00, 1368.70it/s]
100%|██████████| 16/16 [00:00<00:00, 1421.44it/s]
100%|██████████| 15/15 [00:00<00:00, 1130.72it/s]
100%|██████████| 17/17 [00:00<00:00, 1077.01it/s]
100%|██████████| 41/41 [00:00<00:00, 1176.36it/s]
100%|██████████| 14/14 [00:00<00:00, 1133.64it/s]
100%|██████████| 19/19 [00:00<00:00, 1203.99it/s]
100%|██████████| 30/30 [00:00<00:00, 1244.31it/s]
100%|██████████| 26/26 [00:00<00:00, 1330.37it/s]
100%|██████████| 5/5 [00:00<00:00, 910.78it/s]
100%|██████████| 23/23 [00:00<00:00, 1283.46it/s]
100%|██████████| 21/21 [00:00<00:00, 1248.13it/s]
100%|██████████| 55/55 [00:00<00:00, 1460.48it/s]
100%|██████████| 45/45 [00:00<00:00, 1342.94it/s]
100%|██████████| 8/8 [00:00<00:00, 1156.49it/s]
100%|██████████| 130/130 [00:00<00:00, 1382.23it/s]
100%|██████████| 10/10 [00:00<00:00, 1490.20it/s]
100%|██████████| 37/37 [00:00<00:00, 1331.99it/s]
100%|██████████| 46/46 [00:00<00:00, 1384.62it/s]
100%|██████████| 10/10 [00:00<00:00, 1257.70it/s]
100%|██████████| 23/23 [00:00<00:00, 1294.96it/s]
100%|██████████| 23/23 [00:00<00:00, 936.80it/s]
100%|██████████| 148/148 [00:00<00:00, 1322.05it/s]
100%|██████████| 32/32 [00:00<00:00, 1551.35it/s]
100%|██████████| 7/7 [00:00<00:00, 1005.97it/s]
100%|██████████| 20/20 [00:00<00:00, 1219.56it/s]
100%|██████████| 16/16 [00:00<00:00, 1341.27it/s]
100%|██████████| 18/18 [00:00<00:00, 929.85it/s]
100%|██████████| 4/4 [00:00<00:00, 1222.83it/s]
100%|██████████| 32/32 [00:00<00:00, 1202.23it/s]
100%|██████████| 5/5 [00:00<00:00, 1417.47it/s]
100%|██████████| 20/20 [00:00<00:00, 832.15it/s]
100%|██████████| 8/8 [00:00<00:00, 1124.70it/s]
100%|██████████| 14/14 [00:00<00:00, 1433.85it/s]
100%|██████████| 17/17 [00:00<00:00, 1118.81it/s]
100%|██████████| 13/13 [00:00<00:00, 1042.56it/s]
100%|██████████| 11/11 [00:00<00:00, 1362.19it/s]
100%|██████████| 11/11 [00:00<00:00, 1055.03it/s]
100%|██████████| 10/10 [00:00<00:00, 1297.82it/s]
100%|██████████| 18/18 [00:00<00:00, 1451.62it/s]
100%|██████████| 6/6 [00:00<00:00, 729.55it/s]
100%|██████████| 13/13 [00:00<00:00, 1328.35it/s]