## 对最后的统计结果（pha，wise）处理

In [1]:
import numpy as np
import pandas as pd
from urllib.request import urlopen
from requests.api import request
from tqdm import tqdm
raw_data = pd.read_table('mpc_final_sort.txt')

/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.8) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "

In [2]:
data = raw_data[:230]
data

           Name   Diam    type          PHA  time
0      2019 NC1  0.137    Aten         Near  2021
1       2020 MV  0.062  Apollo         Near  2020
2      2020 QU4  0.142    Amor         Near  2020
3      2020 BJ4  0.124  Apollo  Potentially  2020
4     2020 BN11  0.090  Apollo         Near  2020
..          ...    ...     ...          ...   ...
225    2010 KX7  0.124    Aten  Potentially  2010
226  2010 HX107  0.057    Aten         Near  2010
227   2009 UX17  0.149    Amor         Near  2010
228   2010 HW81  0.156  Apollo         Near  2010
229    2000 AA6  0.113  Apollo         Near  2010

[230 rows x 5 columns]

In [3]:
pha = data['PHA'].value_counts()
wise = data['time'].value_counts()
type = data['type'].value_counts()
print(pha,'\n\n',wise,'\n\n',type)

Near           178
Potentially     49
-1               3
Name: PHA, dtype: int64

 2010    55
2016    44
2015    30
2017    26
2014    25
2018    18
2019    15
2020    13
2013     2
2021     1
2011     1
Name: time, dtype: int64

 Apollo    161
Amor       42
Aten       24
Main        3
Name: type, dtype: int64

In [31]:
data2 = data.sort_values(by=['PHA','time','Diam'],ascending=False,ignore_index=True)
data3 = data2[:49]
data3.to_csv('pha.txt',sep='\t')
data4 = data.sort_values(by=['Diam'],ascending=False,ignore_index=True)
data5 = data4[105:230]
data5 = data5.sort_values(by=['time','Diam'],ascending=True,ignore_index=True)
data5[0:50]

          Name   Diam    type   PHA  time
0   2010 BH115  0.000    Main    -1  2010
1    2010 JX16  0.000    Main    -1  2010
2    2010 NS36  0.000    Main    -1  2010
3    2010 EX11  0.045    Aten  Near  2010
4     2010 MY1  0.049  Apollo  Near  2010
5     2010 FE7  0.054  Apollo  Near  2010
6   2010 HX107  0.057    Aten  Near  2010
7    2010 KP10  0.062  Apollo  Near  2010
8    2010 FG81  0.065    Amor  Near  2010
9      1996 GQ  0.071    Amor  Near  2010
10   2010 LL68  0.078  Apollo  Near  2010
11    2008 NP3  0.081  Apollo  Near  2010
12   2010 AJ30  0.084    Aten  Near  2010
13   2010 CB55  0.086  Apollo  Near  2010
14  2016 UH101  0.086  Apollo  Near  2010
15   2010 LJ68  0.086  Apollo  Near  2010
16  2010 LV108  0.090    Amor  Near  2010
17   2010 CC55  0.094  Apollo  Near  2010
18   2010 LK68  0.094  Apollo  Near  2010
19  2010 HZ104  0.094  Apollo  Near  2010
20   2010 GP67  0.094  Apollo  Near  2010
21  2010 CN141  0.098  Apollo  Near  2010
22   2010 FA81  0.098    Amor  Near  2010
23    2010 QA5  0.103    Amor  Near  2010
24   2011 BY24  0.090  Apollo  Near  2011
25   2014 AG16  0.086  Apollo  Near  2013
26   2014 MF18  0.018    Aten  Near  2014
27  2014 QT295  0.020  Apollo  Near  2014
28     2014 FD  0.024  Apollo  Near  2014
29   2014 KO76  0.049  Apollo  Near  2014
30   2014 RH12  0.059    Amor  Near  2014
31   2014 VP35  0.065  Apollo  Near  2014
32   2014 BE63  0.068  Apollo  Near  2014
33   2014 JL25  0.075  Apollo  Near  2014
34    2014 VG2  0.086  Apollo  Near  2014
35    2014 MS5  0.086  Apollo  Near  2014
36   2014 NM64  0.090    Amor  Near  2014
37     2014 CR  0.094  Apollo  Near  2014
38  2014 SD224  0.100    Aten  Near  2014
39   2015 VU65  0.016  Apollo  Near  2015
40   2015 YC18  0.026  Apollo  Near  2015
41  2015 XO129  0.027  Apollo  Near  2015
42     2015 XE  0.034  Apollo  Near  2015
43   2015 PK57  0.039  Apollo  Near  2015
44  2015 HX181  0.049  Apollo  Near  2015
45     2015 QG  0.052  Apollo  Near  2015
46    2015 VF1  0.052  Apollo  Near  2015
47  2015 HU171  0.054  Apollo  Near  2015
48  2015 FN120  0.059  Apollo  Near  2015
49  2015 VZ145  0.059  Apollo  Near  2015