## 抓取MPC上小行星的数据(new)
作者：AstroHHQ  判断mp的类型 是否是PHA

load import & minorplanet list

In [2]:
#load import
import numpy as np
import pandas as pd
from urllib.request import urlopen
from requests.api import request

mpcdata = pd.read_table('mpc.txt')
#mpcdata.sort_values('Diam',ascending=False)
sort_data = mpcdata.sort_values('Diam',ascending=False)
#mpcdata['Name'][0]
mp_name = mpcdata.loc[:,['Name','Diam','H']]
mp_name.insert(2,'type','?')
mp_name['PHA'] = -1# -1:dont know  0: no  1:is potentially hazadous asteriod!
mp_name

            Name   Diam type      H  PHA
0        1991 VA  0.017    ?  26.21   -1
1       1994 CJ1  0.156    ?  21.40   -1
2        1995 CR  0.130    ?  21.80   -1
3        1995 HM  0.094    ?  22.50   -1
4        1996 GQ  0.071    ?  23.10   -1
...          ...    ...  ...    ...  ...
1310   2011 LT17  0.134    ?  21.73   -1
1311   2014 AY28  0.122    ?  21.93   -1
1312  2014 QX266  0.091    ?  22.58   -1
1313  2015 BY310  0.130    ?  21.79   -1
1314     2012 NP  0.160    ?  21.34   -1

[1315 rows x 5 columns]

creat a new list of minorplanet(record it`s type and if pha)

no.16,1206-1246,1282 无法读取

In [3]:
df  = mp_name
df['search?'] = True
df['search?'][16,1282]  = False
df['search?'][1209:1246]  = False
df[1200:1250]

/tmp/ipykernel_319888/2666359979.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['search?'][16,1282]  = False
/home/astrohhq/.local/lib/python3.8/site-packages/pandas/core/indexing.py:1732: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_block(indexer, value, name)
/tmp/ipykernel_319888/2666359979.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['search?'][1209:1246]  = False

                           Name   Diam type      H  PHA  search?
1200                  2021 GQ10  0.014    ?  26.65   -1     True
1201                   2021 HC3  0.143    ?  21.59   -1     True
1202                    2021 HN  0.012    ?  26.90   -1     True
1203                   2021 JB6  0.005    ?  28.78   -1     True
1204                   2021 JR3  0.030    ?  24.95   -1     True
1205                   2021 KN2  0.006    ?  28.63   -1     True
1206                   2021 NY1  0.119    ?  21.98   -1     True
1207                    2021 RS  0.027    ?  25.18   -1     True
1208                   2021 UH2  0.026    ?  25.31   -1     True
1209                333P/LINEAR    NaN    ?    NaN   -1    False
1210       47P/Ashbrook-Jackson    NaN    ?    NaN   -1    False
1211           49P/Arend-Rigaux    NaN    ?    NaN   -1    False
1212  67P/Churyumov-Gerasimenko    NaN    ?    NaN   -1    False
1213                  93P/Lovas    NaN    ?    NaN   -1    False
1214              94P/Russell 4    NaN    ?    NaN   -1    False
1215     C/2017 T2  (PanSTARRS)    NaN    ?    NaN   -1    False
1216                     Derm0f  0.135    ?  21.71   -1    False
1217                     Derm1a  0.079    ?  22.88   -1    False
1218                     Derm1c  0.133    ?  21.74   -1    False
1219                     Derm2g  0.155    ?  21.41   -1    False
1220                     Derm3h  0.094    ?  22.49   -1    False
1221                     Derm3k  0.107    ?  22.22   -1    False
1222                     Derm4c  0.103    ?  22.31   -1    False
1223                     Derm5f  0.130    ?  21.80   -1    False
1224                     Derm5i  0.149    ?  21.50   -1    False
1225                     Derm6c  0.147    ?  21.53   -1    False
1226                     Derm6e  0.094    ?  22.50   -1    False
1227                     Derm6f  0.103    ?  22.31   -1    False
1228                     Derm6k  0.117    ?  22.02   -1    False
1229                     Derm7d  0.118    ?  22.00   -1    False
1230                     Derm7e  0.110    ?  22.14   -1    False
1231                     Derm7o  0.148    ?  21.52   -1    False
1232                     Derm8e  0.094    ?  22.49   -1    False
1233                P/2006 HR30    NaN    ?    NaN   -1    False
1234                P/2016 BA14    NaN    ?    NaN   -1    False
1235                     P000DV    NaN    ?    NaN   -1    False
1236                     P000K7    NaN    ?    NaN   -1    False
1237                     P000TQ    NaN    ?    NaN   -1    False
1238                     P000ZE    NaN    ?    NaN   -1    False
1239                     P0012V    NaN    ?    NaN   -1    False
1240                     P001GV    NaN    ?    NaN   -1    False
1241                     P002I1    NaN    ?    NaN   -1    False
1242                     P002I6    NaN    ?    NaN   -1    False
1243                     P002RZ    NaN    ?    NaN   -1    False
1244                       YORP  0.086    ?  22.70   -1    False
1245                    Mjolnir  0.142    ?  21.60   -1    False
1246                   2003 MA3  0.136    ?  21.70   -1     True
1247                  2000 EH26  0.136    ?  21.70   -1     True
1248                  1996 XB27  0.136    ?  21.70   -1     True
1249                    2006 UP  0.075    ?  23.00   -1     True

### re匹配
.* 贪婪  
.* ? 惰性

In [3]:
import requests as rq
from tqdm import tqdm
import time
import re

测试单个search

In [4]:
url = f'https://minorplanetcenter.net/db_search/show_object?utf8=%E2%9C%93&object_id=2008+ev5'
head ={
    'User-Agent':'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:94.0) Gecko/20100101 Firefox/94.0'
}
s = rq.session()
s.keep_alive = False
s.proxies = {'https':'183.220.195.163:80'}
#s.headers = head
resp = s.get(url)

In [5]:
#space to "+"
#name = mp_name[5]
#name = name.replace(' ','+')
lenMp = len(df)
total = 0
for i in tqdm(range(lenMp)):
   time.sleep(0.2)
   if i%100==0:time.sleep(3)
   #search true or false
   if df['search?'][i]:
      if i%10==0:time.sleep(1)
      name = df['Name'][i]
      name = name.replace(' ','+')
      #get url from mpc
      url = f'https://minorplanetcenter.net/db_search/show_object?utf8=%E2%9C%93&object_id={name}'
      head ={
         'User-Agent':'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:94.0) Gecko/20100101 Firefox/94.0'
      }
      s = rq.session()
      s.keep_alive = False
      s.proxies = {'https':'183.220.195.163:80'}
      #s.headers = head
      resp = s.get(url)
      #regular str
      obj = re.compile(r'Orbit type:\s(?P<tt>\w{1,})\n..<br>\n{2}.{5}(?P<pha>\w{1,})',re.S)
      res = obj.search(resp.text)
      df['type'][i] = res.group('tt')
      df['PHA'][i] = res.group('pha')

  0%|          | 0/1315 [00:00<?, ?it/s]/tmp/ipykernel_2657237/3633101578.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['type'][i] = res.group('tt')
/tmp/ipykernel_2657237/3633101578.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['PHA'][i] = res.group('pha')
/home/astrohhq/.local/lib/python3.8/site-packages/pandas/core/indexing.py:1732: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_block(indexer, value, name)
 18%|█▊        | 234/1315 [09:06<42:06,  2.34s/it]

AttributeError: 'NoneType' object has no attribute 'group'

In [6]:
df.loc[230:234]

           Name   Diam    type   PHA  search?
230   2010 AJ30  0.084    Aten  Near     True
231   2010 AL30  0.011  Apollo  Near     True
232    2010 AN2  0.108  Apollo  Near     True
233     2010 BC  0.108  Apollo  Near     True
234  2010 BH115  0.000       ?    -1     True

In [7]:
for i in tqdm(range(235,lenMp)):
   time.sleep(0.2)
   if i%100==0:time.sleep(3)
   #search true or false
   if df['search?'][i]:
      if i%10==0:time.sleep(1)
      name = df['Name'][i]
      name = name.replace(' ','+')
      #get url from mpc
      url = f'https://minorplanetcenter.net/db_search/show_object?utf8=%E2%9C%93&object_id={name}'
      head ={
         'User-Agent':'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:94.0) Gecko/20100101 Firefox/94.0'
      }
      s = rq.session()
      s.keep_alive = False
      s.proxies = {'https':'183.220.195.163:80'}
      #s.headers = head
      resp = s.get(url)
      #regular str
      obj = re.compile(r'Orbit type:\s(?P<tt>\w{1,})\n..<br>\n{2}.{5}(?P<pha>\w{1,})',re.S)
      res = obj.search(resp.text)
      df['type'][i] = res.group('tt')
      df['PHA'][i] = res.group('pha')

  0%|          | 0/1080 [00:00<?, ?it/s]/tmp/ipykernel_2657237/878334576.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['type'][i] = res.group('tt')
  5%|▌         | 59/1080 [02:18<40:00,  2.35s/it]

AttributeError: 'NoneType' object has no attribute 'group'

检查发现，有的主带小行星得重新写正则

In [23]:
obj = re.compile(r'Orbit type:\s(?P<tt>\w{1,})',re.S)
res = obj.search(resp.text)
if res is not None:print('5')
obj2 = re.compile(r'Orbit type:\s(?P<tt>\w{1,})\n..<br>\n{2}.{5}(?P<pha>\w{1,})',re.S)
res2 = obj2.search(resp.text)
if res2 is None:print("none")

5
none

In [21]:
df.loc[292:295]

          Name   Diam    type   PHA  search?
292  2010 JO71  0.049  Apollo  Near     True
293  2010 JW39  0.037  Apollo  Near     True
294  2010 JX16  0.000       ?    -1     True
295   2010 KA8  0.156       ?    -1     True

In [25]:
for i in tqdm(range(294,lenMp)):
   time.sleep(0.2)
   if i%100==0:time.sleep(3)
   #search true or false
   if df['search?'][i]:
        if i%10==0:time.sleep(1)
        name = df['Name'][i]
        name = name.replace(' ','+')
        #get url from mpc
        url = f'https://minorplanetcenter.net/db_search/show_object?utf8=%E2%9C%93&object_id={name}'
        head ={
        'User-Agent':'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:94.0) Gecko/20100101 Firefox/94.0'
        }
        s = rq.session()
        s.keep_alive = False
        s.proxies = {'https':'183.220.195.163:80'}
        #s.headers = head
        resp = s.get(url)
        #regular str
        obj = re.compile(r'Orbit type:\s(?P<tt>\w{1,})',re.S)
        res = obj.search(resp.text)
        df['type'][i] = res.group('tt')
        obj2 = re.compile(r'Orbit type:\s(?P<tt>\w{1,})\n..<br>\n{2}.{5}(?P<pha>\w{1,})',re.S)
        res2 = obj2.search(resp.text)
        if res2 is not None:df['PHA'][i] = res2.group('pha')

  0%|          | 0/1021 [00:00<?, ?it/s]/tmp/ipykernel_2657237/3739890335.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['type'][i] = res.group('tt')
100%|██████████| 1021/1021 [40:22<00:00,  2.37s/it]

df.loc[234]前面的234重新处理

In [33]:
i = 234
name = df['Name'][i]
name = name.replace(' ','+')
#get url from mpc
url = f'https://minorplanetcenter.net/db_search/show_object?utf8=%E2%9C%93&object_id={name}'
head ={
'User-Agent':'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:94.0) Gecko/20100101 Firefox/94.0'
}
s = rq.session()
s.keep_alive = False
s.proxies = {'https':'183.220.195.163:80'}
#s.headers = head
resp = s.get(url)
#regular str
obj = re.compile(r'Orbit type:\s(?P<tt>\w{1,})',re.S)
res = obj.search(resp.text)
df['type'][i] = res.group('tt')
obj2 = re.compile(r'Orbit type:\s(?P<tt>\w{1,})\n..<br>\n{2}.{5}(?P<pha>\w{1,})',re.S)
res2 = obj2.search(resp.text)
if res2 is not None:df['PHA'][i] = res2.group('pha')

/tmp/ipykernel_2657237/2590100468.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['type'][i] = res.group('tt')

In [36]:
df.to_csv('mpc_wise_type_nha.txt',sep='\t',index=False)